### PR TITLE
Add quit command

### LINKED ISSUE #84: no quit command

### PR DESCRIPTION
**Pull request by zhiayang**
Closes #84

### CODE REVIEW

**Comment by fall9x** [comment]
Looks good

**Comment by zhiayang** [comment]
branch is even with master, plz merge

**Comment by fall9x** [comment]
> branch is even with master, plz merge

Opps gotta update

**Comment by zhiayang** [comment]
done

**Comment by fall9x** [comment]
oof actually would it be bad practice for me to press the update branch button for u?

**Comment by fall9x** [comment]
Looks good to merge!

**Pull request merged**
