### PR TITLE
Recipe pane opens when a recipe is created

### LINKED ISSUE #166: Recipe pane should be opened when a recipe is created
like how edit works

### PR DESCRIPTION
**Pull request by fall9x**
Closes #166

### CODE REVIEW

**Comment by seowalex** [comment]
I'm current using a event listener in `DisplayController` to switch views based on whether recipes are add/edited/deleted, so we probably shouldn't do this.

**Comment by fall9x** [comment]
oof okay didnt see that, will amend

**Comment by fall9x** [comment]
> I'm current using a event listener in `DisplayController` to switch views based on whether recipes are add/edited/deleted, so we probably shouldn't do this.

okay changed

**Comment by zhiayang** [comment]
👍

**Pull request merged**
